platform :ios, '8.0'
use_frameworks!

source 'git@git.silvrr.com:iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'BannerView_Example' do

  pod 'BannerView', :path => '../'

  # pod 'Base', :path => '../'
  # pod 'Network', '~> 0.1.0'

  # target 'BannerView_Tests' do
  #   inherit! :search_paths
  #
  #
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
